<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <ul class="list-group">
            <?php if(count($rooms) == 0): ?>
                <span class="text-danger"><?php echo "there is no room, base on input id" ;?></span>
            <?php else: ?>
                <?php foreach($rooms as &$room): ?>
                    <li class="list-group-item">
                        <p><?php echo "{$room['roomid']} | <span class='label label-default'>{$room['roomname']}</span> - {$room['description']} - {$room['created']}";?> </p>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>
</div>