<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="/join" method="POST" class="form-group">
                <input type="text" name="user[name]" placeholder="name" class="form-control"/>
                <input type="text" name="user[email]" placeholder="email" class="form-control"/>
                <input type="text" name="user[password]" placeholder="password" class="form-control"/>
                <button class="btn btn-default">join</button>
            </form>
        </div>
    </div>
</div>